### ISSUE TITLE
No support for APSE2?

### ISSUE THREAD

**Issue by paulwakeford** [pahud/ec2spot#1]
curl  -s https://ec2spot.com/current-spot-price/ap-southeast-2/Linux/m4.large
{"errorMessage":"invalid region: ap-southeast-2"}

**Comment by pahud** [comment]
thanks, I just added it in.

current supported regions:

```
        'us-east-1',
        'us-west-1',
        'us-west-2',
        'eu-west-1',
        'eu-central-1',
        'ap-southeast-1',
        'ap-southeast-2',
        'ap-south-1',
        'ap-northeast-1',
        'ap-northeast-2',
        'sa-east-1'
```

Have fun!

**Comment by paulwakeford** [comment]
Just a thought, but for future maintainability why not use the output of

aws ec2 describe-regions

?

**Comment by pahud** [comment]
thanks for our nice suggestion. I'll add this in shortly. 👍
